// Generated by gencpp from file nvi_msgs/CompressedRGBDImage.msg
// DO NOT EDIT!


#ifndef NVI_MSGS_MESSAGE_COMPRESSEDRGBDIMAGE_H
#define NVI_MSGS_MESSAGE_COMPRESSEDRGBDIMAGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/CompressedImage.h>
#include <sensor_msgs/Image.h>

namespace nvi_msgs
{
template <class ContainerAllocator>
struct CompressedRGBDImage_
{
  typedef CompressedRGBDImage_<ContainerAllocator> Type;

  CompressedRGBDImage_()
    : header()
    , rgb()
    , depth()  {
    }
  CompressedRGBDImage_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , rgb(_alloc)
    , depth(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::sensor_msgs::CompressedImage_<ContainerAllocator>  _rgb_type;
  _rgb_type rgb;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _depth_type;
  _depth_type depth;





  typedef boost::shared_ptr< ::nvi_msgs::CompressedRGBDImage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nvi_msgs::CompressedRGBDImage_<ContainerAllocator> const> ConstPtr;

}; // struct CompressedRGBDImage_

typedef ::nvi_msgs::CompressedRGBDImage_<std::allocator<void> > CompressedRGBDImage;

typedef boost::shared_ptr< ::nvi_msgs::CompressedRGBDImage > CompressedRGBDImagePtr;
typedef boost::shared_ptr< ::nvi_msgs::CompressedRGBDImage const> CompressedRGBDImageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nvi_msgs::CompressedRGBDImage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nvi_msgs::CompressedRGBDImage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nvi_msgs::CompressedRGBDImage_<ContainerAllocator1> & lhs, const ::nvi_msgs::CompressedRGBDImage_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.rgb == rhs.rgb &&
    lhs.depth == rhs.depth;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nvi_msgs::CompressedRGBDImage_<ContainerAllocator1> & lhs, const ::nvi_msgs::CompressedRGBDImage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nvi_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::nvi_msgs::CompressedRGBDImage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nvi_msgs::CompressedRGBDImage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nvi_msgs::CompressedRGBDImage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nvi_msgs::CompressedRGBDImage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nvi_msgs::CompressedRGBDImage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nvi_msgs::CompressedRGBDImage_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nvi_msgs::CompressedRGBDImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9ced99430bcd6c0b779e815bf297af1c";
  }

  static const char* value(const ::nvi_msgs::CompressedRGBDImage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9ced99430bcd6c0bULL;
  static const uint64_t static_value2 = 0x779e815bf297af1cULL;
};

template<class ContainerAllocator>
struct DataType< ::nvi_msgs::CompressedRGBDImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nvi_msgs/CompressedRGBDImage";
  }

  static const char* value(const ::nvi_msgs::CompressedRGBDImage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nvi_msgs::CompressedRGBDImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"sensor_msgs/CompressedImage rgb\n"
"sensor_msgs/Image depth\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/CompressedImage\n"
"# This message contains a compressed image\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"\n"
"string format        # Specifies the format of the data\n"
"                     #   Acceptable values:\n"
"                     #     jpeg, png\n"
"uint8[] data         # Compressed image buffer\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
;
  }

  static const char* value(const ::nvi_msgs::CompressedRGBDImage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nvi_msgs::CompressedRGBDImage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.rgb);
      stream.next(m.depth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CompressedRGBDImage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nvi_msgs::CompressedRGBDImage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nvi_msgs::CompressedRGBDImage_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "rgb: ";
    s << std::endl;
    Printer< ::sensor_msgs::CompressedImage_<ContainerAllocator> >::stream(s, indent + "  ", v.rgb);
    s << indent << "depth: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.depth);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NVI_MSGS_MESSAGE_COMPRESSEDRGBDIMAGE_H
