// Generated by gencpp from file nvi_msgs/HeaderFloat32.msg
// DO NOT EDIT!


#ifndef NVI_MSGS_MESSAGE_HEADERFLOAT32_H
#define NVI_MSGS_MESSAGE_HEADERFLOAT32_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace nvi_msgs
{
template <class ContainerAllocator>
struct HeaderFloat32_
{
  typedef HeaderFloat32_<ContainerAllocator> Type;

  HeaderFloat32_()
    : header()
    , data(0.0)  {
    }
  HeaderFloat32_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::nvi_msgs::HeaderFloat32_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nvi_msgs::HeaderFloat32_<ContainerAllocator> const> ConstPtr;

}; // struct HeaderFloat32_

typedef ::nvi_msgs::HeaderFloat32_<std::allocator<void> > HeaderFloat32;

typedef boost::shared_ptr< ::nvi_msgs::HeaderFloat32 > HeaderFloat32Ptr;
typedef boost::shared_ptr< ::nvi_msgs::HeaderFloat32 const> HeaderFloat32ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nvi_msgs::HeaderFloat32_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nvi_msgs::HeaderFloat32_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nvi_msgs::HeaderFloat32_<ContainerAllocator1> & lhs, const ::nvi_msgs::HeaderFloat32_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nvi_msgs::HeaderFloat32_<ContainerAllocator1> & lhs, const ::nvi_msgs::HeaderFloat32_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nvi_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::nvi_msgs::HeaderFloat32_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nvi_msgs::HeaderFloat32_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nvi_msgs::HeaderFloat32_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nvi_msgs::HeaderFloat32_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nvi_msgs::HeaderFloat32_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nvi_msgs::HeaderFloat32_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nvi_msgs::HeaderFloat32_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef848af8cf12f6df11682cc76fba477b";
  }

  static const char* value(const ::nvi_msgs::HeaderFloat32_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef848af8cf12f6dfULL;
  static const uint64_t static_value2 = 0x11682cc76fba477bULL;
};

template<class ContainerAllocator>
struct DataType< ::nvi_msgs::HeaderFloat32_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nvi_msgs/HeaderFloat32";
  }

  static const char* value(const ::nvi_msgs::HeaderFloat32_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nvi_msgs::HeaderFloat32_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 data\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::nvi_msgs::HeaderFloat32_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nvi_msgs::HeaderFloat32_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HeaderFloat32_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nvi_msgs::HeaderFloat32_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nvi_msgs::HeaderFloat32_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data: ";
    Printer<float>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NVI_MSGS_MESSAGE_HEADERFLOAT32_H
