// Generated by gencpp from file nvi_msgs/stamp_float32array.msg
// DO NOT EDIT!


#ifndef NVI_MSGS_MESSAGE_STAMP_FLOAT32ARRAY_H
#define NVI_MSGS_MESSAGE_STAMP_FLOAT32ARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace nvi_msgs
{
template <class ContainerAllocator>
struct stamp_float32array_
{
  typedef stamp_float32array_<ContainerAllocator> Type;

  stamp_float32array_()
    : header()
    , data()  {
    }
  stamp_float32array_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::nvi_msgs::stamp_float32array_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nvi_msgs::stamp_float32array_<ContainerAllocator> const> ConstPtr;

}; // struct stamp_float32array_

typedef ::nvi_msgs::stamp_float32array_<std::allocator<void> > stamp_float32array;

typedef boost::shared_ptr< ::nvi_msgs::stamp_float32array > stamp_float32arrayPtr;
typedef boost::shared_ptr< ::nvi_msgs::stamp_float32array const> stamp_float32arrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nvi_msgs::stamp_float32array_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nvi_msgs::stamp_float32array_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nvi_msgs::stamp_float32array_<ContainerAllocator1> & lhs, const ::nvi_msgs::stamp_float32array_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nvi_msgs::stamp_float32array_<ContainerAllocator1> & lhs, const ::nvi_msgs::stamp_float32array_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nvi_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::nvi_msgs::stamp_float32array_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nvi_msgs::stamp_float32array_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nvi_msgs::stamp_float32array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nvi_msgs::stamp_float32array_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nvi_msgs::stamp_float32array_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nvi_msgs::stamp_float32array_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nvi_msgs::stamp_float32array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a120344537a3b099cc9ec9957d4619fc";
  }

  static const char* value(const ::nvi_msgs::stamp_float32array_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa120344537a3b099ULL;
  static const uint64_t static_value2 = 0xcc9ec9957d4619fcULL;
};

template<class ContainerAllocator>
struct DataType< ::nvi_msgs::stamp_float32array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nvi_msgs/stamp_float32array";
  }

  static const char* value(const ::nvi_msgs::stamp_float32array_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nvi_msgs::stamp_float32array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32[] data\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::nvi_msgs::stamp_float32array_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nvi_msgs::stamp_float32array_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct stamp_float32array_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nvi_msgs::stamp_float32array_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nvi_msgs::stamp_float32array_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NVI_MSGS_MESSAGE_STAMP_FLOAT32ARRAY_H
